### ISSUE TITLE
RPM to Hz

### ISSUE THREAD

**Issue by Getiem** [electropaultje/template-itho-daalderop-module#5]
HomeAssistant vind de unitofmeasurement 'rpm' niet OK bij frequency.  Moet Hz worden (omgerekend..)

```
  - platform: modbus_spy
    name: "Outdoor fan setpoint"
    **device_class: "frequency"**
    accuracy_decimals: 0
    state_class: "measurement"
    **unit_of_measurement: "rpm"**
    device_address: 0x02
    register_address: 42105
    filters:
      - delta: 1
  - platform: modbus_spy
    name: "Outdoor fan 1 actual"
    **device_class: "frequency"**
    accuracy_decimals: 0
    state_class: "measurement"
    **unit_of_measurement: "rpm"**
...
```

> Entity sensor.ithodaalderop_outdoor_fan_setpoint (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'rpm' which is not a valid unit for the device class ('frequency') it is using; expected one of ['kHz', 'MHz', 'GHz', 'Hz']; Please update your configuration if your entity is manually configured, otherwise create a bug report at [https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A"integration%3A+esphome"](https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22)
> Entity sensor.ithodaalderop_outdoor_fan_1_actual (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'rpm' which is not a valid unit for the device class ('frequency') it is using; expected one of ['kHz', 'MHz', 'GHz', 'Hz']; Please update your configuration if your entity is manually configured, otherwise create a bug report at [https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A"integration%3A+esphome"](https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22)
